### ISSUE TITLE
Test_away_mode results...

### ISSUE THREAD

**Issue by GaryOkie** [bmenchaca/icomfort3-scraper#1]
I've updated lcc_zone.py and test_away_mode with your latest fixes.    The "homes" error is resolved and the test_away_mode app executes properly, however it is getting a failed response code.

`**python test_away_mode.py**
Starting Away Mode test for homes {'100000': [('0ad0b7ed', '0')]}.
Home 100000, lcc 0ad0b7ed zone 0
**Response code was Fail.**
https://www.lennoxicomfort.com/Dashboard/RefreshLatestZoneDetailByIndex?zoneid=0&isPolling=true&lccid=00ad0b7ed&_=1535569
{'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': 'application/json, text/javascript, */*; q=0.01', 'Connection': 'keep-alive', 'Accept-Language': 'en-US,en;q=0.9', 'DNT': '1', 'Host': 'www.lennoxicomfort.com', 'X-Requested-With': 'XMLHttpRequest', 'ADRUM': 'isAjax:true', 'Referer': 'https://www.lennoxicomfort.com/Dashboard/HomeDetails?zoneId=0&homeId=100000&lccId=00ad0b7ed&refreshZonedetail=False', 'Cookie': 'iComfort=ic3; .AspNet.ApplicationCookie=E0VMtYoCKGTvwER-uHmASP.NET_SessionId=tindtj30xutvkku05r; __RequestVerificationToken=vAhGgUZEU1'}
{'Code': 'Fail', 'Url': '/Account/Login?_isSessionExpired=True'}
Fetch failed, retrying.
Response code was Fail.`

**Comment by bmenchaca** [comment]
This is exactly the redirect I get when I am logged in elsewhere...do you get this regardless?

**Comment by GaryOkie** [comment]
The above test was run from the same wifi network as the S30.  I just reran it from the outside via mobile hotspot and got the same error: 
```
'Code': 'Fail', 'Url': '/Account/Login?_isSessionExpired=True'}
Fetch failed, retrying.)
```
Since the test_update app works fine to pull current settings, there shouldn't be any issue with my id/password.

And thanks for the security advice.   Yeah, I changed the home id, thought that was good enough.   I've changed the lccid as well.

**Comment by bmenchaca** [comment]
That error is strange - let me see if it's perhaps a request ordering/timing issue.  I will do some experiments today.

**Comment by bmenchaca** [comment]
Patch pushed.  I believe the issue is that some magic is happening on the server side that sets context to a particular zone when you navigate in the UI.  If you attempt to change a zone to which you have not navigated, it assumes your client is out of sync.  Please retry with this fix.

**Comment by GaryOkie** [comment]
Ben, good news - test_away_mode runs now just fine once I discovered that the iComfort android app was still running (asleep) in the background.   I sure had not realized I was still logged on as you had warned this would be an issue.   I have not re-tested with your latest patch though.
```
Starting Away Mode test for homes {'100000': [('0ad6ea0b7ed', '0')]}.
Home 100000, lcc 0ad6ea00b7ed, zone 0
Before Set Away: False
After Set Away: True
Home 100000, lcc 0ad6ea00b7ed, zone 0
Before Cancel Away: True
After Cancel Away: False
```

**Comment by bmenchaca** [comment]
Good to hear, but a bit disconcerting regarding multiple app/client interference.  I am worried it’s that timestamp field (_=seconds) that’s desynced between clients.  I will test this.

**Comment by bmenchaca** [comment]
This seems to be working for some definition of working; I don't think the sync issues between clients are anything we can prevent (perhaps mitigate with retries and the like).  OK to close this issue?

**Comment by GaryOkie** [comment]
Sure, we can close this.
